### ISSUE TITLE
Both CramerGAN and MMDGAN export wrong images.

### ISSUE THREAD

**Issue by Joool** [ningyu1991/GANFingerprints#1]
Both CramerGAN and MMDGAN export images with wrong colors:

![CRAMER_00000000](https://user-images.githubusercontent.com/9444447/71968871-f7181f80-3205-11ea-8820-9a214c44af35.png)![CRAMER_00000001](https://user-images.githubusercontent.com/9444447/71968884-fb443d00-3205-11ea-89ba-202d9a3a5dc0.png)![CRAMER_00000002](https://user-images.githubusercontent.com/9444447/71968894-fda69700-3205-11ea-86a0-0944b2614f0b.png)

The error is located in the export images function (equivalent for both GANs):

```python
def inverse_transform(images):
    return (images+1.)/2.


def save_images(images, size, image_path):
    merged = merge(inverse_transform(images), size)
    return scipy.misc.imsave(image_path, merged)
```

Values passed to `save_images` are in the range [0,1]. The call to `inverse_transform` rescales them to [0.5, 1], which in turn causes the pixel values to be only in the range [127.5, 255], instead of [0, 255]. This results in colors only from the brighter part of the spectrum, as shown above.

**Comment by wheatdog** [comment]
I didn't encounter this issue. Both GANs export images correctly. I think `images` are in the range of [-1,1] since the last activation function of generator is sigmoid,
https://github.com/ningyu1991/GANFingerprints/blob/dbae45f3ab66ab41c366cc876d1767e9f9295b03/CramerGAN/gan/core/architecture.py#L115

Thus, the `inverse_transform` is correct.

**Edit: I mistook sigmoid for tanh. All the statement above is nonsense. Please ignore!**

**Comment by Joool** [comment]
[Sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) is in range [0,1]. 
[Tanh](https://en.wikipedia.org/wiki/Hyperbolic_function) is in range [-1, 1]. 

Also the input processing explicitly scales images to the range [0, 1]: 

https://github.com/ningyu1991/GANFingerprints/blob/dbae45f3ab66ab41c366cc876d1767e9f9295b03/CramerGAN/gan/utils/utils.py#L218-L225

Note the `return np.array(cropped_image)/255.`, which scales [0, 255] pixel values to [0, 1].

**Comment by wheatdog** [comment]
Right! Sorry that I mistook sigmoid for tanh. How embarrassing I am! In this case, I am not sure why it works in my end. I will dig into code and report later.

**Comment by wheatdog** [comment]
I found that I am using `scipy==1.2.0`. After consulting to the [documentation](https://docs.scipy.org/doc/scipy-1.2.0/reference/generated/scipy.misc.imsave.html) of `scipy.misc.imsave`, the underlying call to [`scipy.misc.bytescale`](https://docs.scipy.org/doc/scipy-1.2.0/reference/generated/scipy.misc.bytescale.html#scipy.misc.bytescale) might be the reason that it works in my end. It basically maps the lowest value in `images` to 0 and the highest value to 255. So the `inverse_transform` function seems useless and kinda misguiding if so. In my opinion, your transformation is more reasonable. Cheers!
