### ISSUE TITLE
What is the label order for test?

### ISSUE THREAD

**Issue by AEP-WYK** [ningyu1991/GANFingerprints#3]
for example
labels_1 = ['CelebA_real_data', 'ProGAN_generated_data', 'SNGAN_generated_data', 'CramerGAN_generated_data', 'MMDGAN_generated_data']  in util_scripts.py

I've found that if I use a lexicographical order with my own data set, I get an error response

**Comment by ningyu1991** [comment]
Yes, the label order should be that in the code:
['CelebA_real_data', 'ProGAN_generated_data', 'SNGAN_generated_data', 'CramerGAN_generated_data', 'MMDGAN_generated_data']

**Comment by AEP-WYK** [comment]
But in what order should I use my own data set?What is the rule for this order? Thank you

**Comment by ningyu1991** [comment]
If you are using the same set of GAN architectures, for the sake of least risk, try to use the same order as mine. If you are using a different set, choose whatever order is convenient for you, and align them well between training and testing, by modifying my code.

**Comment by AEP-WYK** [comment]
Ok, thank you
